### ISSUE TITLE
Incompatible with Miniflare?

### ISSUE THREAD

**Issue by leviwolfe** [maraisr/workers-logger#3]
I have been using https://miniflare.dev/ for faster development and better local debugging than wrangler. I believe Cloudflare is also officially adopting it in the future. If I add workers-logger to package.json and include this minimal example as my module:

```
import { track } from 'workers-logger';

const reporter = (events) => console.log(events);

const worker = {
	async fetch(request, _env, context) {
		const log = track(request, 'worker-example', reporter);
		log.info('gearing up to make a response');

		const res = new Response('hi there');

		context.waitUntil(log.report(res));
		return res;
	},
};

export default worker;
```

Unfortunately, when I start Miniflare I get the following stack:

```
ReferenceError: process is not defined
    at <truncated>diary@0.2.2\node_modules\diary\diary\node\index.mjs:2:85
    at SourceTextModule.evaluate (node:internal/vm/module:224:23)
    at VMScriptRunner.runAsModule (<truncated>@miniflare+runner-vm@2.0.0-rc.1/node_modules/@miniflare/runner-vm/src/index.ts:38:18)
    at VMScriptRunner.run (<truncated>@miniflare+runner-vm@2.0.0-rc.1/node_modules/@miniflare/runner-vm/src/index.ts:83:17)
    at EventTarget.#reload (<truncated>@miniflare+core@2.0.0-rc.1_@miniflare+watcher@2.0.0-rc.1/node_modules/@miniflare/core/src/index.ts:590:13)
    at EventTarget.getPlugins (<truncated>@miniflare+core@2.0.0-rc.1_@miniflare+watcher@2.0.0-rc.1/node_modules/@miniflare/core/src/index.ts:787:5)
    at createServer (<truncated>@miniflare+http-server@2.0.0-rc.1_@miniflare+watcher@2.0.0-rc.1/node_modules/@miniflare/http-server/src/index.ts:315:19)
    at startServer (<truncated>@miniflare+http-server@2.0.0-rc.1_@miniflare+watcher@2.0.0-rc.1/node_modules/@miniflare/http-server/src/index.ts:383:18)
    at main (<truncated>miniflare@2.0.0-rc.1/node_modules/miniflare/src/cli.ts:89:5)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by maraisr** [comment]
This is not good, it _should_ work. 

Which bundler are you using? workers-logger uses `diary` under-the-hood, which does in fact support node, and browsers. And it uses ["esm exports"](https://github.com/maraisr/diary/blob/f5f0997cc52868b4f2c858e25e243990f7dfd670/package.json#L20-L31) to distinguish the platform.

I personally do use miniflare as well, but with [worktop.build](https://github.com/lukeed/worktop/tree/next/packages/worktop.build) as the builder. 

Anyhow, let me know. I might need to swindle a legacy compliant version of workers-logger (that has a predefined and static target)

**Comment by leviwolfe** [comment]
Thanks. I'm using "rollup -c" as my build command and miniflare ^2.0.0-rc.1 (I can't quite remember why). Here is my current rollup.config.js, and I could try to make a minimal repro repo if you think that will help.

```
import { terser } from 'rollup-plugin-terser';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import json from '@rollup/plugin-json';

export default {
	input: 'src/index.js',
	output: {
		exports: 'named',
		format: 'es',
		file: 'dist/index.mjs',
		sourcemap: true,
	},

	plugins: [commonjs(), json(), nodeResolve({ browser: true }), terser()],
};
```

**Comment by leviwolfe** [comment]
I created [leviwolfe/modules-rollup-esm](https://github.com/leviwolfe/modules-rollup-esm) to repro the problem, and it looks like a Rollup thing, not a Miniflare thing. I started by cloning the [cloudflare/modules-rollup-esm](https://github.com/cloudflare/modules-rollup-esm) example repo, added miniflare and workers-logger. You'll get the same `ReferenceError: process is not defined` error if you use `wrangler dev` or `npm start` (which runs miniflare).

**Comment by maraisr** [comment]
Thank you so much, I'll check this momentarily! Hopefully get you a solution by days end 🤞🏻

**Comment by maraisr** [comment]
I think the issue is that rollup by default doesnt look for the export condition for a `worker` (which I guess is okay from rollup's lens)

In anycase, this should do the trick; https://github.com/leviwolfe/modules-rollup-esm/pull/1

I have however just released a new version of workers logger to updates `diary` so that if you choose to use a module worker, that it'll work there too.

Let me know how that goes? Thank you for this. I might update the docs a little and talk about what sort of settings you may need in popular bundlers — however, I highly recommend using `worktop.build` as suggested earlier 🚀

**Comment by leviwolfe** [comment]
Adding `exportConditions: ['worker']` to the rollup `nodeResolve` got me further along, thanks!

I was still seeing a `Cannot read properties of undefined (reading 'length')` exception until I added a call to `enable()` in `diary` [according to your instructions](https://github.com/maraisr/diary#workers). This was on `let len = allows.length;` in `worker\index.mjs`. Seems like it is working great now. It might be worth adding this to the examples and readme for this repo as well.

I will have to look into `worktop.build` if it can be used independently. I have generally avoided `worktop` as it is a little too abstracted from typical worker code.
