### ISSUE TITLE
localStorage is not defined while using wrangler dev

### ISSUE THREAD

**Issue by lab-bone-Max** [maraisr/workers-logger#5]
### Describe the bug

I have build an API as a CloudFlare Worker written in TypeScript and using Durable Objects (also Stripe, Supabase and AWS-SES) so using the module based syntax for my worker.
The relevant module versions I'm using:
```
		"diary": "0.4.0",
		"wrangler": "^2.1.10",
		"workers-logger": "^0.2.0"
```
I have written a reporter that submits all queued log messages to LogFlare but I did the development with a hacked version of diary as diary/diary/browser refers to localStorage in global context which does not exist in a Cloudflare Worker module.

I got a more permanent solution that works with the npm version of diary by adding the following to the plugins section of my webpack.config:
```
	new webpack.DefinePlugin({
		'localStorage': {getItem: ()=>undefined},
	}),
```
 This is mostly likely resolvable in Diary but as both modules are maintained by same owner, and this seems to be more specific to Cloudflare workers, hence I am filing the issue here.

### To reproduce

The following exception occurs shortly after calling the track() function of workers-logger

```
Error on remote worker: ParseError: A request to the Cloudflare API (/accounts/3e82c433807fb3387b58886da196b9c9/workers/scripts/www-api-dev/edge-preview) failed.

      at throwFetchError
  (/Users/max.lyth/github.nosync/lab-web-api/node_modules/wrangler/wrangler-dist/cli.js:143359:17)
      at fetchResult
  (/Users/max.lyth/github.nosync/lab-web-api/node_modules/wrangler/wrangler-dist/cli.js:143328:5)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async createPreviewToken
  (/Users/max.lyth/github.nosync/lab-web-api/node_modules/wrangler/wrangler-dist/cli.js:143641:29)
      at async createWorkerPreview
  (/Users/max.lyth/github.nosync/lab-web-api/node_modules/wrangler/wrangler-dist/cli.js:143661:17)
      at async start
  (/Users/max.lyth/github.nosync/lab-web-api/node_modules/wrangler/wrangler-dist/cli.js:144311:34) {
    text: 'A request to the Cloudflare API
  (/accounts/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/workers/scripts/www-api-dev/edge-preview) failed.',
    notes: [
      {
        text: 'Uncaught ReferenceError: localStorage is not defined\n' +
          '  at worker.js:71029:12 in
  ./node_modules/workers-logger/node_modules/diary/diary/browser/index.mjs\n' +
          '  at worker.js:71123:33 in __webpack_require__\n' +
          '  at worker.js:67793:55 in ./src/v4_2/_libs/logger.ts\n' +
          '  at worker.js:71123:33 in __webpack_require__\n' +
          '  at worker.js:69039:53 in ./src/v4_2/products-prices/products-prices.ts\n' +
          '  at worker.js:71123:33 in __webpack_require__\n' +
          '  at worker.js:69024:57 in ./src/v4_2/products-prices/index.ts\n' +
          '  at worker.js:71123:33 in __webpack_require__\n' +
          '  at worker.js:68937:57 in ./src/v4_2/index.ts\n' +
          '  at worker.js:71123:33 in __webpack_require__\n' +
          ' [code: 10021]'
      }
    ],
    location: undefined,
    kind: 'error',
    code: 10021
  }
```

### Expected behavior

The code should check that localStorage object is defined before invoking a method

### Validations

- [X] Follow our [Code of Conduct](https://github.com/maraisr/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/maraisr/.github/blob/main/CONTRIBUTING.md).
- [ ] Is there already an issue for this?

**Comment by maraisr** [comment]
Hi there, thanks for the issue — sounds to me like your module resolutions isn't configured correctly within your bundler. 

I see youre using webpack, please put this in and let me know how it goes:

```js
conditionNames: [
   "worker", // 👈 important part
   "browser", "import", "require", "node", "default"
]
```

[learn more](https://webpack.js.org/configuration/resolve/#resolveconditionnames)

`diary` which powers workers-logger [does ship](https://github.com/maraisr/diary/blob/main/package.json#L20-L24) with the correct conditions, see package: https://unpkg.com/browse/diary@0.4.1/diary/worker/index.mjs
